### ISSUE TITLE
Slicer generates infill inside gap fill/perimeters

### ISSUE THREAD

**Issue by Nbeknel** [supermerill/Slic3r#4670]
### What happened?

When slicing a model with thin areas (e.g. chimney of Benchy) the slicer generates infill in addition to/on top of gap fill and perimeters in these areas.
This issue seemingly goes away when disabling `Allow Periemter inside Gap fill`, although, if you scroll further down to the steering wheel, the same issue still occurs.

Benchy + hollow cylinder (top - `Allow Periemter inside Gap fill` enabled, bottom - `Allow Periemter inside Gap fill` disabled):

Top layer:
<img width="984" height="731" alt="Image" src="https://github.com/user-attachments/assets/1c40e4a0-3033-4e26-b038-524f6aec9ac3" />

Chimney:
<img width="975" height="731" alt="Image" src="https://github.com/user-attachments/assets/2c6d47f4-b1a3-470b-8cef-60046a27d845" />

Steering wheel:
<img width="1163" height="854" alt="Image" src="https://github.com/user-attachments/assets/c447c299-bfdd-41a8-8e76-1a0cf0d6af50" />

### Project file & How to reproduce

[Infill-Gap_fill-Overlap.zip](https://github.com/user-attachments/files/21915930/Infill-Gap_fill-Overlap.zip)

### Version

2.7.61.8

### Operating system

Windows 10

**Comment by supermerill** [comment]
you can try the nightly, it should be working on it.

**Comment by macchinette** [comment]
> you can try the nightly, it should be working on it.

Hi Supermerill, I tried the attached project by Nbeknel and found that the problem is still not solved.
I used two versions on Windows.

Build: SuperSlicer_2.7.61.9

Build: SuperSlicer_2.7.62.0-2025-09-01

Regards

**Comment by supermerill** [comment]
Will be Fixed in next nightly & release

**Comment by macchinette** [comment]
> Will be Fixed in next nightly & release

Perfect, thank you very much! This version solved the problem:

Version: 2.7.61.9
Build: SuperSlicer_2.7.61.9-2025-09-05
